#!/bin/bash
#
# pve-optimize.sh
# Безопасная оптимизация Proxmox VE под большой сервер + ZFS + K8s
#
# Делает:
#  - ZFS ARC min/max (по умолчанию 128G/256G)
#  - ZFS: compression, atime=off, xattr=sa (на ZFS_POOL, наследуется дочерними)
#  - sysctl: conntrack, inotify, file-max, swappiness, dirty ratios, numa_balancing=0, ip_forward
#  - modules: nf_conntrack, br_netfilter через modules-load.d
#
# Опционально:
#  - сетевые буферы (выключено по умолчанию, включи ENABLE_NET_BUFFERS=1)
#  - zstd компрессия (по умолчанию lz4)
#
# Использование:
#   ./pve-optimize.sh                              # дефолтные настройки
#   ARC_MIN_GB=64 ARC_MAX_GB=128 ./pve-optimize.sh # кастомный ARC
#   ENABLE_NET_BUFFERS=1 ./pve-optimize.sh         # включить сетевые буферы
#   ZFS_COMPRESSION=zstd ./pve-optimize.sh         # zstd вместо lz4
#
# После выполнения нужен reboot для применения ARC.
#
set -euo pipefail

### ====== НАСТРОЙКИ (можно переопределить через ENV) ======

# ZFS ARC размеры в гигабайтах
ARC_MIN_GB="${ARC_MIN_GB:-128}"
ARC_MAX_GB="${ARC_MAX_GB:-256}"

# ZFS pool для тюнинга
ZFS_POOL="${ZFS_POOL:-rpool}"

# Компрессия: lz4 (безопасно) или zstd (лучше сжатие на современных CPU)
ZFS_COMPRESSION="${ZFS_COMPRESSION:-lz4}"

# Сетевые буферы для 10G+ (включай если реально нужно)
ENABLE_NET_BUFFERS="${ENABLE_NET_BUFFERS:-0}"

# Bridge netfilter (нужно для K8s/iptables на мостах)
ENABLE_BR_NETFILTER="${ENABLE_BR_NETFILTER:-1}"

# Conntrack
NF_CONNTRACK_MAX="${NF_CONNTRACK_MAX:-1048576}"
NF_CONNTRACK_EST_TIMEOUT="${NF_CONNTRACK_EST_TIMEOUT:-86400}"

### =========================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_err()   { echo -e "${RED}[ERROR]${NC} $1"; }
log_debug() { echo -e "${BLUE}[DEBUG]${NC} $1"; }

need_root() {
    if [[ ${EUID} -ne 0 ]]; then
        log_err "Скрипт должен запускаться от root"
        exit 1
    fi
}

need_pve() {
    if ! command -v pveversion >/dev/null 2>&1; then
        log_err "Proxmox VE не обнаружен (нет pveversion)"
        exit 1
    fi
}

show_hardware_info() {
    echo ""
    log_info "Hardware:"
    
    # RAM
    local ram_gb
    ram_gb=$(awk '/MemTotal/{printf "%.0f", $2/1024/1024}' /proc/meminfo)
    log_debug "  RAM: ${ram_gb} GB"
    
    # CPU
    local cpu_cores cpu_model
    cpu_cores=$(nproc)
    cpu_model=$(grep -m1 "model name" /proc/cpuinfo | cut -d: -f2 | xargs)
    log_debug "  CPU: ${cpu_model} (${cpu_cores} cores)"
    
    # ZFS pool size
    if zpool list "$ZFS_POOL" >/dev/null 2>&1; then
        local pool_size pool_free
        pool_size=$(zpool list -H -o size "$ZFS_POOL")
        pool_free=$(zpool list -H -o free "$ZFS_POOL")
        log_debug "  ZFS pool '${ZFS_POOL}': ${pool_size} total, ${pool_free} free"
    fi
    
    echo ""
}

backup_file() {
    local f="$1"
    if [[ -f "$f" ]]; then
        local ts
        ts=$(date +%Y%m%d-%H%M%S)
        cp -a "$f" "${f}.bak.${ts}"
        log_info "Backup: ${f}.bak.${ts}"
    fi
}

gb_to_bytes() {
    local gb="$1"
    echo $(( gb * 1024 * 1024 * 1024 ))
}

apply_zfs_arc() {
    local arc_min_b arc_max_b
    arc_min_b=$(gb_to_bytes "$ARC_MIN_GB")
    arc_max_b=$(gb_to_bytes "$ARC_MAX_GB")

    if [[ "$arc_min_b" -ge "$arc_max_b" ]]; then
        log_err "ARC_MIN_GB (${ARC_MIN_GB}) должен быть меньше ARC_MAX_GB (${ARC_MAX_GB})"
        exit 1
    fi

    local conf="/etc/modprobe.d/zfs.conf"
    backup_file "$conf"

    cat > "$conf" <<EOF
# ZFS ARC Memory Configuration
# Generated by pve-optimize.sh on $(date -Is)
#
# ARC Min: ${ARC_MIN_GB} GiB
# ARC Max: ${ARC_MAX_GB} GiB
#
options zfs zfs_arc_min=${arc_min_b}
options zfs zfs_arc_max=${arc_max_b}
EOF

    log_info "ZFS ARC: min=${ARC_MIN_GB}G, max=${ARC_MAX_GB}G -> ${conf}"
}

tune_zfs_pool() {
    if ! zpool list "$ZFS_POOL" >/dev/null 2>&1; then
        log_warn "ZFS pool '${ZFS_POOL}' не найден — пропускаю настройку dataset"
        return 0
    fi

    log_info "Настройка ZFS pool '${ZFS_POOL}'..."

    # compression
    if zfs set compression="$ZFS_COMPRESSION" "$ZFS_POOL" 2>/dev/null; then
        log_info "  compression=${ZFS_COMPRESSION}"
    else
        log_warn "  compression уже установлен или ошибка"
    fi

    # atime=off — уменьшает write IOPS
    if zfs set atime=off "$ZFS_POOL" 2>/dev/null; then
        log_info "  atime=off"
    else
        log_warn "  atime уже отключен или ошибка"
    fi

    # xattr=sa — хранить xattr в inode (быстрее)
    if zfs set xattr=sa "$ZFS_POOL" 2>/dev/null; then
        log_info "  xattr=sa"
    else
        log_warn "  xattr=sa уже установлен или ошибка"
    fi
}

write_sysctl() {
    local conf="/etc/sysctl.d/99-pve-optimize.conf"
    backup_file "$conf"

    cat > "$conf" <<EOF
# Proxmox VE Optimization
# Generated by pve-optimize.sh on $(date -Is)

# ===== Conntrack (K8s/NAT/много соединений) =====
net.netfilter.nf_conntrack_max=${NF_CONNTRACK_MAX}
net.netfilter.nf_conntrack_tcp_timeout_established=${NF_CONNTRACK_EST_TIMEOUT}

# ===== Forwarding (VM/CT/K8s) =====
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
EOF

    if [[ "${ENABLE_BR_NETFILTER}" == "1" ]]; then
        cat >> "$conf" <<EOF

# ===== Bridge netfilter (iptables на мостах) =====
net.bridge.bridge-nf-call-iptables=1
net.bridge.bridge-nf-call-ip6tables=1
EOF
    fi

    cat >> "$conf" <<EOF

# ===== Memory =====
vm.swappiness=10

# Dirty thresholds для NVMe
vm.dirty_ratio=10
vm.dirty_background_ratio=5
vm.dirty_expire_centisecs=3000
vm.dirty_writeback_centisecs=500

# ===== K8s/inotify =====
fs.inotify.max_user_watches=1048576
fs.inotify.max_user_instances=8192
fs.inotify.max_queued_events=32768

# ===== File descriptors =====
fs.file-max=2097152
fs.nr_open=2097152

# ===== NUMA =====
kernel.numa_balancing=0

# ===== rp_filter (loose для overlay/VXLAN) =====
net.ipv4.conf.all.rp_filter=2
net.ipv4.conf.default.rp_filter=2
EOF

    if [[ "${ENABLE_NET_BUFFERS}" == "1" ]]; then
        cat >> "$conf" <<EOF

# ===== Network buffers (10G+) =====
net.core.rmem_max=134217728
net.core.wmem_max=134217728
net.core.rmem_default=31457280
net.core.wmem_default=31457280
net.ipv4.tcp_rmem=4096 87380 134217728
net.ipv4.tcp_wmem=4096 65536 134217728
net.core.netdev_max_backlog=250000
net.ipv4.tcp_max_syn_backlog=8192
net.ipv4.tcp_slow_start_after_idle=0
EOF
    fi

    log_info "sysctl -> ${conf}"
}

write_modules() {
    local conf="/etc/modules-load.d/pve-optimize.conf"
    backup_file "$conf"

    cat > "$conf" <<EOF
# Generated by pve-optimize.sh on $(date -Is)
nf_conntrack
EOF

    if [[ "${ENABLE_BR_NETFILTER}" == "1" ]]; then
        echo "br_netfilter" >> "$conf"
    fi

    log_info "modules-load.d -> ${conf}"

    # Загружаем модули сейчас
    modprobe nf_conntrack >/dev/null 2>&1 || true
    if [[ "${ENABLE_BR_NETFILTER}" == "1" ]]; then
        modprobe br_netfilter >/dev/null 2>&1 || true
    fi
}

update_initramfs_safe() {
    log_info "Обновление initramfs..."
    if ! update-initramfs -u -k all; then
        log_warn "update-initramfs завершился с ошибкой (не критично)"
    fi
}

apply_sysctl_now() {
    log_info "Применение sysctl..."
    sysctl --system >/dev/null 2>&1 || true
}

print_summary() {
    echo ""
    echo "========================================"
    echo "  Оптимизация завершена"
    echo "========================================"
    echo ""
    echo "Конфигурация:"
    echo "  ZFS pool:        ${ZFS_POOL}"
    echo "  ZFS compression: ${ZFS_COMPRESSION}"
    echo "  ZFS ARC:         ${ARC_MIN_GB}G min / ${ARC_MAX_GB}G max"
    echo "  Conntrack max:   ${NF_CONNTRACK_MAX}"
    echo "  Net buffers:     ${ENABLE_NET_BUFFERS}"
    echo "  BR netfilter:    ${ENABLE_BR_NETFILTER}"
    echo ""
    echo "Файлы:"
    echo "  /etc/modprobe.d/zfs.conf"
    echo "  /etc/sysctl.d/99-pve-optimize.conf"
    echo "  /etc/modules-load.d/pve-optimize.conf"
    echo ""
    log_warn "ТРЕБУЕТСЯ REBOOT для применения ZFS ARC"
    echo ""
}

main() {
    need_root
    need_pve

    echo "========================================"
    echo "  Proxmox VE Optimization Script"
    echo "========================================"
    pveversion || true
    
    show_hardware_info

    apply_zfs_arc
    tune_zfs_pool
    write_sysctl
    write_modules
    update_initramfs_safe
    apply_sysctl_now
    print_summary

    read -r -p "Перезагрузить сейчас? (y/N): " ans || true
    if [[ "${ans:-}" == "y" || "${ans:-}" == "Y" ]]; then
        log_info "Перезагрузка..."
        reboot
    else
        log_info "Не забудь: reboot"
    fi
}

main "$@"
